"""
Export the trait vector artifact bank to review-friendly files.

Outputs (under data/processed/vector_artifacts/):
    system_prompts_review.csv        — all system prompts with trait/pole/id/text
    elicitation_questions_review.csv — all questions with trait/split/id/text
    rubrics_review.md                — rubrics in Markdown for human review

Usage:
    python scripts/export_vector_artifacts_for_review.py
    python scripts/export_vector_artifacts_for_review.py --out-dir path/to/dir
"""

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from src.vectors.artifact_bank import load_artifact_bank  # noqa: E402


def _write_rubrics_md(bank, out_path: Path) -> None:
    lines: list[str] = [
        "# Trait Evaluation Rubrics — Review Copy",
        "",
        "> Generated by `scripts/export_vector_artifacts_for_review.py`.",
        "> These rubrics are used when judging model responses to elicitation questions.",
        "> They are part of the persona-vector construction pipeline and are separate",
        "> from the ETHICS item bank used for projection and reliability testing.",
        "",
    ]

    for _, row in bank.rubrics_df.iterrows():
        trait = row["trait"]
        lines += [
            f"## {trait.capitalize()}",
            "",
            f"**Score range:** {row['min_score']} – {row['max_score']}",
            "",
            "### Scoring instructions",
            "",
            str(row["scoring_instructions"]).strip(),
            "",
        ]

        # Pull positive/negative examples from raw YAML
        rubric_raw = bank.raw.get(trait, {}).get("evaluation_rubric", {})
        pos_examples = rubric_raw.get("positive_examples", [])
        neg_examples = rubric_raw.get("negative_examples", [])

        scale = rubric_raw.get("score_scale", {}).get("interpretation", {})
        if scale:
            lines += ["### Score interpretation", ""]
            for score_val, desc in sorted(scale.items()):
                lines.append(f"- **{score_val}**: {str(desc).strip()}")
            lines.append("")

        if pos_examples:
            lines += ["### Positive examples (score ≈ 100)", ""]
            for ex in pos_examples:
                lines.append(f"> {str(ex).strip()}")
                lines.append("")

        if neg_examples:
            lines += ["### Negative examples (score ≈ 0)", ""]
            for ex in neg_examples:
                lines.append(f"> {str(ex).strip()}")
                lines.append("")

        lines.append("---")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export trait vector artifacts to CSV/Markdown for review."
    )
    parser.add_argument(
        "--artifacts-path",
        default=str(_ROOT / "configs" / "trait_vector_artifacts.yaml"),
        help="Path to trait_vector_artifacts.yaml",
    )
    parser.add_argument(
        "--out-dir",
        default=str(_ROOT / "data" / "processed" / "vector_artifacts"),
        help="Output directory",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        bank = load_artifact_bank(args.artifacts_path)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}")
        sys.exit(1)

    prompts_path = out_dir / "system_prompts_review.csv"
    questions_path = out_dir / "elicitation_questions_review.csv"
    rubrics_path = out_dir / "rubrics_review.md"

    bank.system_prompts_df.to_csv(prompts_path, index=False)
    bank.questions_df.to_csv(questions_path, index=False)
    _write_rubrics_md(bank, rubrics_path)

    print("=" * 64)
    print("  Trait Vector Artifact Bank — Export Complete")
    print("=" * 64)
    print(f"  System prompts CSV    : {prompts_path}")
    print(f"  Questions CSV         : {questions_path}")
    print(f"  Rubrics Markdown      : {rubrics_path}")
    print()
    print(f"  System prompts total  : {len(bank.system_prompts_df)}")
    print(f"  Questions total       : {len(bank.questions_df)}")
    print(f"  Rubrics total         : {len(bank.rubrics_df)}")
    print()
    print("  Review these files before proceeding to Stage 2B.")
    print("  These artifacts are separate from the ETHICS item bank.")
    print()
    print("  Recommended next step: run the quality audit")
    print("    python scripts/audit_vector_artifacts.py")
    print("  Saves: data/processed/vector_artifacts/vector_artifact_audit.csv")
    print("         data/processed/vector_artifacts/vector_artifact_audit.md")
    print("=" * 64)


if __name__ == "__main__":
    main()
